/*
Copyright 2017 IBM Corp.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
*/

public class AlertDetails {
    @AuraEnabled public String areaName;
    @AuraEnabled public String headline;
    @AuraEnabled public String description;
    @AuraEnabled public String overview;
    @AuraEnabled public String instruction;
}